openapi: 3.1.0

info:
  title: Lab 1 API
  version: 1.0.0
  description: API para o Lab1.

servers:
  - url: http://localhost:3000
    description: Servidor local

paths:
  /:
    get:
      summary: Verifica que a API está a funcionar
  /health:
    get:
      summary: Verifica o estado da API
  /api/items:
    get:
      summary: Lista todos os itens
      parameters:
        - name: name
          in: query
          required: false
          schema:
            type: string
            minLength: 1
        - name: sort
          in: query
          required: false
          schema:
            type: string
            enum: [name, id]
        - name: order
          in: query
          required: false
          schema:
            type: string
            enum: [asc, desc]
        - name: page
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            default: 10 

      responses:
        '200':
          description: Lista de itens (paginada ou total)
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/PaginatedItems'
                  - type: array
                    items:
                      $ref: '#/components/schemas/Item'
        '400':
          description: Pedido inválido
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Item:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: Item 1
      required:
        - id
        - name  
    PaginatedItems:
      type: object
      properties:
        page:
          type: integer
        limit:
          type: integer
        items:
          type: array
          items:
            $ref: '#/components/schemas/Item'
    Error:
      type: object
      properties:
        error:
          type: string
        required:
          - error

